### ISSUE TITLE
Changing the app icon

### ISSUE THREAD

**Issue by QuangDNguyen2211** [QuangDNguyen2211/Image-Editor#6]
The app icon is the default Android icon, and I want to change it. I dont have any requirement for it, so you can be creative about what you want to do

**Comment by Young-Tran** [comment]
can you assign me this issue

**Comment by Young-Tran** [comment]
![image](https://user-images.githubusercontent.com/26095382/143982674-6eda7a5a-923c-493a-b2d1-35f6a4074ee5.png)
is that fine

**Comment by QuangDNguyen2211** [comment]
yea that looks good
